### ISSUE TITLE
Keys in import-wallet key path can't be found

### ISSUE THREAD

**Issue by agermain** [stereum-dev/ethereum2-ansible#82]
The following lines: 
https://github.com/stereum-dev/ethereum2-ansible/blob/main/import-validator-accounts.yaml#L16-L20

Work under the assumption that those files are visibible to the `stereum`, which might not be the case when for example the keys are SCP'd to the root user. This means the import-wallet step fails when these cannot be seen by that user.

**Comment by gbayasgalan** [comment]
The promlem was, if the key-files in `/root/...` (not in /home/MyUser/...) directory then it cannot copy the key-files to `project/launchpad` directory, because of `user: stereum` https://github.com/stereum-dev/ethereum2-ansible/blob/main/import-validator-accounts.yaml#L19. 

Now the task `copy-key-files` https://github.com/stereum-dev/ethereum2-ansible/blob/main/import-validator-accounts.yaml#L16 works without `user: stereum` which allows to copy the `key-files` from both `/root/...` and `/home/MyUser/...` into `project/launchpad`. After that we set the permissions to the copied files in `project/launchpad`
